---
- search:
    provider: google
    target: _blank
    focus: true

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
    units: metric
    refresh: 3000
    label: Homepage Server
